spring:
  application:
    name: carteira-digital-crud-api
  datasource:
    url: jdbc:postgresql://localhost:5432/carteira_digital_crud_db
    username: postgres
    password: senha123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true