create table usuarios (
    ativo boolean not null,
    saldo numeric(38,2) not null,
    id bigint generated by default as identity,
    cpf varchar(14) not null unique,
    email varchar(100) not null unique,
    nome varchar(100) not null,
    senha varchar(255) not null,
    primary key (id)
)