create table transacoes (
                            id bigint generated by default as identity,
                            valor numeric(38,2) not null,
                            data_criacao timestamp(6) not null,
                            usuario_id bigint not null,
                            primary key (id)
);
alter table if exists transacoes
    add constraint FK_usuario_transacao
        foreign key (usuario_id) references usuarios;