create table transacoes (
    valor numeric(38,2) not null,
    data_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    usuario_id bigint not null,
    tipo varchar(255) not null check (
        (tipo in ('DEPOSITO', 'SAQUE', 'TRANSFERENCIA'))
        ),
    primary key (id)
)